### ISSUE TITLE
Exception: The conversion cannot be performed

### ISSUE THREAD

**Issue by lorenzstadler** [Tyr3al/N26ToYNAB#1]
The tool does not work for me unfortunately.

I am not even sure if you want to maintain it or have time to work on other peoples errors, but just in case you do, here is my bug report. I would be thankful if you looked into it.

Console output:
```
$ ./N26ToYNAB-0.1.0-win-x64.exe -i defect_n26-csv-transactions.csv
Started Conversion
Trying to parse input file defect_n26-csv-transactions.csv
Could read / parse input file!
Exception: The conversion cannot be performed.
    Text: ''
    MemberType: System.Decimal
    TypeConverter: 'CsvHelper.TypeConversion.DecimalConverter'
IReader state:
   ColumnCount: 0
   CurrentIndex: 6
   HeaderRecord:
["Datum","Empfänger","Kontonummer","Transaktionstyp","Verwendungszweck","Betrag (EUR)","Betrag (Fremdwährung)","Fremdwährung","Wechselkurs"]
IParser state:
   ByteCount: 0
   CharCount: 235
   Row: 2
   RawRow: 2
   Count: 9
   RawRecord:
"2023-02-01","Von Hauptkonto nach N","","Überweisung","Monatliche Überweisung","-30.0","","",""
```

Attached you can find the csv file.
[defect_n26-csv-transactions.csv](https://github.com/Tyr3al/N26ToYNAB/files/11304818/defect_n26-csv-transactions.csv)

**Comment by Tyr3al** [comment]
Thanks for the report! N26 apparently changed their CSV export format. I'll upload a fix in a few moments.

**Comment by lorenzstadler** [comment]
Thank you! It worked perfectly now. 👍
